"""Prompt templates for documentation, evaluation, code generation, and tests."""
from src.prompts.documenter_prompts import (
    DOCUMENTER_SYSTEM_PROMPT,
    DOCUMENTER_USER_PROMPT,
    DOC_REFINER_SYSTEM_PROMPT,
    DOC_REFINER_USER_PROMPT
)
from src.prompts.evaluator_prompts import (
    DOC_EVALUATOR_SYSTEM_PROMPT,
    DOC_EVALUATOR_USER_PROMPT,
    CODE_EVALUATOR_SYSTEM_PROMPT,
    CODE_EVALUATOR_USER_PROMPT,
    CHUNK_EVALUATOR_SYSTEM_PROMPT,
    CHUNK_EVALUATOR_USER_PROMPT,
    DEPENDENCY_EVALUATOR_SYSTEM_PROMPT,
    DEPENDENCY_EVALUATOR_USER_PROMPT
)
from src.prompts.codegen_prompts import (
    CODEGEN_SYSTEM_PROMPT,
    CODEGEN_USER_PROMPT,
    CODE_REFINER_SYSTEM_PROMPT,
    CODE_REFINER_USER_PROMPT,
    TESTGEN_SYSTEM_PROMPT,
    TESTGEN_USER_PROMPT
)

__all__ = [
    "DOCUMENTER_SYSTEM_PROMPT",
    "DOCUMENTER_USER_PROMPT",
    "DOC_REFINER_SYSTEM_PROMPT",
    "DOC_REFINER_USER_PROMPT",
    "DOC_EVALUATOR_SYSTEM_PROMPT",
    "DOC_EVALUATOR_USER_PROMPT",
    "CODE_EVALUATOR_SYSTEM_PROMPT",
    "CODE_EVALUATOR_USER_PROMPT",
    "CHUNK_EVALUATOR_SYSTEM_PROMPT",
    "CHUNK_EVALUATOR_USER_PROMPT",
    "DEPENDENCY_EVALUATOR_SYSTEM_PROMPT",
    "DEPENDENCY_EVALUATOR_USER_PROMPT",
    "CODEGEN_SYSTEM_PROMPT",
    "CODEGEN_USER_PROMPT",
    "CODE_REFINER_SYSTEM_PROMPT",
    "CODE_REFINER_USER_PROMPT",
    "TESTGEN_SYSTEM_PROMPT",
    "TESTGEN_USER_PROMPT"
]
